services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    # volumes:
    #   - ../:/workspaces/dev-container:cached
    #   - node_modules:/workspaces/dev-container/node_modules
    command: sleep infinity
volumes:
  node_modules:
