services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    # volumes:
    #   - ../:/workspaces/dev-container:cached
    #   - node_modules:/workspaces/dev-container/node_modules
    command: sleep infinity
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  node_modules:
  postgres-data:
